/**
 * Фото по смыслу пункта (индекс = порядок в JSON расписания).
 * Файлы в папке places/: часть с Wikimedia Commons, часть тематический Unsplash.
 */
window.EVENT_IMAGES = [
  ["places/kutaisi-airport.jpg", "places/airport-terminal.jpg"],
  ["places/road-cafe-georgia.jpg", "places/restaurant-interior.jpg"],
  ["places/tbilisi-houses.jpg", "places/tbilisi-panorama.jpg"],
  ["places/peace-bridge.jpg", "places/kartlis-deda.jpg"],
  ["places/old-tbilisi.jpg", "places/restaurant-interior.jpg"],
  ["places/breakfast-table.jpg", "places/tbilisi-houses.jpg"],
  ["places/chronicle-georgia.jpg", "places/jvari.jpg"],
  ["places/mtskheta-svetitskhoveli.jpg", "places/restaurant-interior.jpg"],
  ["places/mountain-pass-road.jpg", "places/caucasus-landscape.jpg"],
  ["places/borjomi-park.jpg", "places/borjomi-town.jpg"],
  ["places/borjomi-town.jpg", "places/restaurant-interior.jpg"],
  ["places/highway-night-lights.jpg", "places/batumi-boulevard.jpg"],
  ["places/batumi-boulevard.jpg", "places/batumi-aerial.jpg"],
  ["places/breakfast-table.jpg", "places/hotel-resort-pool.jpg"],
  ["places/waterfall-nature.jpg", "places/valley-landscape.jpg"],
  ["places/waterfall-nature.jpg", "places/cafe-dining.jpg"],
  ["places/metal-sculpture.jpg", "places/batumi-aerial.jpg"],
  ["places/cafe-dining.jpg", "places/hotel-resort-pool.jpg"],
  ["places/batumi-dusk.jpg", "places/seaside-ferris.jpg"],
  ["places/architecture-plaza.jpg", "places/coastal-city-view.jpg"],
  ["places/breakfast-table.jpg", "places/clothing-bazaar.jpg"],
  ["places/clothing-bazaar.jpg", "places/mall-interior.jpg"],
  ["places/restaurant-interior.jpg", "places/cafe-dining.jpg"],
  ["places/mall-interior.jpg", "places/architecture-plaza.jpg"],
  ["places/coastal-city-view.jpg", "places/batumi-aerial.jpg"],
  ["places/turkish-spread.jpg", "places/restaurant-interior.jpg"],
  ["places/breakfast-table.jpg", "places/botanical-garden.jpg"],
  ["places/botanical-garden.jpg", "places/valley-landscape.jpg"],
  ["places/grilled-fish.jpg", "places/restaurant-interior.jpg"],
  ["places/vegetable-stall.jpg", "places/clothing-bazaar.jpg"],
  ["places/batumi-boulevard.jpg", "places/hotel-resort-pool.jpg"],
  ["places/city-tower-modern.jpg", "places/coastal-city-view.jpg"],
  ["places/breakfast-table.jpg", "places/hotel-resort-pool.jpg"],
  ["places/hotel-resort-pool.jpg", "places/airport-terminal.jpg"],
  ["places/hotel-resort-pool.jpg", "places/kutaisi-airport.jpg"],
  ["places/borscht-bowl.jpg", "places/restaurant-interior.jpg"],
  ["places/mountain-pass-road.jpg", "places/caucasus-landscape.jpg"],
  ["places/river-pedestrian-bridge.jpg", "places/caucasus-landscape.jpg"],
  ["places/bar-lights.jpg", "places/restaurant-interior.jpg"],
  ["places/river-pedestrian-bridge.jpg", "places/bar-lights.jpg"],
  ["places/breakfast-table.jpg", "places/prometheus-cave.jpg"],
  ["places/prometheus-cave.jpg", "places/canyon-river.jpg"],
  ["places/dumplings-plate.jpg", "places/road-cafe-georgia.jpg"],
  ["places/canyon-river.jpg", "places/waterfall-nature.jpg"],
  ["places/restaurant-interior.jpg", "places/road-cafe-georgia.jpg"],
  ["places/breakfast-table.jpg", "places/airport-terminal.jpg"],
  ["places/airport-terminal.jpg", "places/kutaisi-airport.jpg"],
];
